<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Seeking Work In_AgreedToEula</name>
   <tag></tag>
   <elementGuidId>30cac6ff-5a21-4638-8105-b1889622a9ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AgreedToEula']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AgreedToEula</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d8d13f8-2279-40a9-98b7-2bab08dceab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>90ff87a7-d1e4-467d-a73d-6466941a9218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0fc83782-b22a-4ccf-889e-aa4de83546d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-hasacceptedterms</name>
      <type>Main</type>
      <value>You must accept the End User License Agreement</value>
      <webElementGuid>3ee653f6-594b-476b-8d07-e18c48056b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>You must accept the End User License Agreement</value>
      <webElementGuid>8844d04e-c578-432a-ae01-245470861961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AgreedToEula</value>
      <webElementGuid>d3190709-09dd-4765-8307-eac86baf2e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AgreedToEula</value>
      <webElementGuid>33a9bdfc-ba85-44ac-b6cf-ec25e2027b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a4ad1549-beb0-437c-82ec-101592b8a67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AgreedToEula&quot;)</value>
      <webElementGuid>74f1ce6d-7a1f-45f0-9ee7-b9fdb2aa29f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AgreedToEula']</value>
      <webElementGuid>f259cc77-be3b-4877-a1be-243233f9ec0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='renderedBody']/form/div[6]/input</value>
      <webElementGuid>29bd9079-ba6e-4052-bd26-a1c627b90e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>e159aa19-ea72-4687-b411-4626720604a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'AgreedToEula' and @name = 'AgreedToEula']</value>
      <webElementGuid>41a90df7-0dcc-4370-88fe-0d3d5b45354a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
